######## Encryption Configuration #####
jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD}
        algorithm: PBEWithMD5AndTripleDES
        

logging.level:
  org.springframework.cloud: DEBUG
  com.dreamsoftware.epg: DEBUG